# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 00:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adopter', models.NullBooleanField(default=None)),
                ('fosterer', models.NullBooleanField(default=None)),
                ('breed', models.TextField(default='')),
                ('size', models.TextField(default='')),
                ('age', models.TextField(default='')),
                ('zip_code', models.TextField(default='')),
                ('city', models.TextField(default='')),
                ('paragraph', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField(default='')),
                ('preferences', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.Preference')),
            ],
        ),
    ]
