# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 00:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_id', models.TextField()),
                ('name', models.TextField()),
                ('sex', models.TextField()),
                ('age', models.TextField()),
                ('contact_email', models.TextField()),
                ('contact_phone', models.TextField()),
                ('city', models.TextField()),
                ('zip_code', models.TextField()),
                ('size', models.TextField()),
                ('description', models.TextField()),
                ('adoptable', models.NullBooleanField(default=None)),
                ('fosterable', models.NullBooleanField(default=None)),
                ('breeds', models.ManyToManyField(to='dogs.Breed')),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('dog', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dogs.Dog')),
            ],
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_url', models.TextField()),
                ('dog', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dogs.Dog')),
            ],
        ),
    ]
