# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='name',
            field=models.TextField(default='hello'),
        ),
    ]
