# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 23:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0002_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='favorites',
        ),
        migrations.AddField(
            model_name='dog',
            name='favorites',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dogs.User'),
        ),
    ]
