# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 12:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0004_notes_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='dog',
            field=models.ForeignKey(default='none', on_delete=django.db.models.deletion.CASCADE, to='dogs.Dog'),
        ),
        migrations.AlterField(
            model_name='photos',
            name='dog',
            field=models.ForeignKey(default='none', on_delete=django.db.models.deletion.CASCADE, to='dogs.Dog'),
        ),
    ]
