# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 23:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0004_auto_20160501_2331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='favorites',
        ),
        migrations.AddField(
            model_name='user',
            name='favorites',
            field=models.ManyToManyField(default=None, null=True, to='dogs.Dog'),
        ),
    ]
