# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 23:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0005_auto_20160501_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favorites',
            field=models.ManyToManyField(default=None, to='dogs.Dog'),
        ),
    ]
