# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 02:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0007_dog_profile_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='profile_photo_url',
            field=models.CharField(default='', max_length=200),
        ),
    ]
